version: '3.8'

services:
  frontend:
    image: "${FRONTEND_IMAGE_NAME}:${FRONTEND_IMAGE_TAG}"
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend1:
    image: "${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}"
    container_name: backend1
    ports:
      - "5000:5000"
    networks:
      - app-network
  backend2:
   image: "${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}"
   container_name: backend2
   ports:
     - "5001:5000"
   networks:
     - app-network

networks:
  app-network:
    driver: bridge

