name: CD Workflow
on:
  workflow_run:
    workflows: [CI Workflow]
    types: [completed]
    branches: [dev]
    
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22

      - name: Delete existing .env and docker-compose.yml on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "rm -f /home/ubuntu/.env /home/ubuntu/docker-compose.yaml || true"

      - name: Copy docker-compose.yml and .env to EC2
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yaml .env ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Run docker-compose down on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu && docker-compose down || true"

      - name: Run docker-compose up on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu && docker-compose up -d"
